# Generated by Django 5.2.10 on 2026-01-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountPhase',
            new_name='DealPhase',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='value',
        ),
    ]
