# Generated by Django 5.2.10 on 2026-01-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_accountphase_dealphase_remove_account_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.account'),
        ),
        migrations.AddField(
            model_name='deal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.dealphase'),
        ),
        migrations.AddField(
            model_name='deal',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
