# Generated by Django 5.2.10 on 2026-01-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deal_account_deal_name_deal_stage_deal_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
