# Generated by Django 5.2.10 on 2026-02-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activity_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Produktnamn')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Artikelnummer')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Listpris')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Inköpspris/Kostnad')),
                ('product_type', models.CharField(choices=[('service', 'Tjänst'), ('hardware', 'Hårdvara'), ('software', 'Mjukvara'), ('subscription', 'Prenumeration')], default='service', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkter',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.deal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
    ]
